// <auto-generated />
namespace TestIdentity2018.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Addingnewcolumns : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Addingnewcolumns));
        
        string IMigrationMetadata.Id
        {
            get { return "201803011817144_Adding new columns"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
